# Generated by Django 3.2.6 on 2022-02-02 00:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='dateline',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
